connection_string = "postgres://postgres:postgres@localhost:5432/postgres"
output_path = "src/generated"
schemas = ["api"]

[types]
ltree = "String"

[exceptions]
P0001 = "Sample error"

[task_queue]
schema = "tasks"
task_name_column = "task_name"
payload_column = "payload"
